### ISSUE TITLE
哪个提交的comfyui

### ISSUE THREAD

**Issue by ningpengtao-coder** [bobvinch/comfy-server#5]
请问你使用的是哪个提交的comfyui，目前我使用最新的，插件ComfyUI-Impact-Pack有错误。
[WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work.
string indices must be integers, not 'str'
Error handling request
Traceback (most recent call last):
  File "/home/ai/miniconda3/envs/comfyui/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/miniconda3/envs/comfyui/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/miniconda3/envs/comfyui/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/projects/ComfyUI/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/projects/ComfyUI/server.py", line 53, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/projects/ComfyUI/server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/projects/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by bobvinch** [comment]
2月份以前，不要使用太新的版本，有几个节点兼容性经常出问题，像这个和效率节点
